# Configuration Schema Definition

environment:
  type: dict
  required:
    mode:
      type: str
      allowed: [development, production, test]
    debug:
      type: bool
    log_level:
      type: str
      allowed: [DEBUG, INFO, WARNING, ERROR, CRITICAL]

api:
  type: dict
  required:
    port:
      type: int
      min: 1024
      max: 65535
    host:
      type: str
    rate_limit:
      type: int
      min: 1
    timeout:
      type: int
      min: 1

trading:
  type: dict
  required:
    mode:
      type: str
      allowed: [simulated, paper, live]
    initial_balance:
      type: float
      min: 0
    base_currency:
      type: str
    max_risk:
      type: float
      min: 0
      max: 1
    max_position_size:
      type: float
      min: 0
# Add other sections as needed for your system
